// Seed source for `npm run seed-products`.
// Each item is one row in the Product collection. The `images` array lists
// filenames that exist in /products/ at the repo root; seedProducts.js will
// upload each to Cloudinary and replace the array with secure_urls before
// inserting the document.
//
// Categories preserved verbatim from /products/aaaProductDetails.ts.
// Units lowercased to match the Product schema enum
// (['kg','litre','dozen','piece','grams','ml']).

module.exports = [
  { name: 'Fresh Anjir', price: 280, description: 'Premium dried figs with natural sweetness and chewy texture. Packed with dietary fiber, minerals, and antioxidants. Perfect as a healthy snack or adding to desserts and salads.', category: 'Dry Fruits', stockUnit: 'kg', tags: ['Dry Fruits','Anjir','Fig','Healthy','Nutritious'], images: ['Fresh-Anjir.jpg'] },
  { name: 'Fresh Avocado', price: 150, description: 'Creamy avocados with rich, buttery texture and mild flavor. Great for salads, toasts, and smoothies. Loaded with healthy fats, fiber, and essential vitamins for balanced nutrition.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Avocado','Exotic','Healthy Fats','Organic'], images: ['Fresh-Avocado.jpg','Fresh-Avocado-2.jpg'] },
  { name: 'Fresh Banana', price: 40, description: 'Sweet yellow bananas naturally ripened for perfect taste. Rich in potassium and energy-boosting carbohydrates. Ideal for breakfast, smoothies, or as a quick healthy snack anytime.', category: 'Fresh Fruit', stockUnit: 'dozen', tags: ['Fresh Fruit','Banana','Yellow','Energy','Potassium'], images: ['Fresh-Banana.jpg'] },
  { name: 'Fresh Beetroot', price: 35, description: 'Vibrant red beets with earthy sweetness and firm texture. Excellent for salads, juices, or roasting. High in nitrates, fiber, and essential minerals supporting overall health.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Beetroot','Red','Healthy','Root Vegetable'], images: ['Fresh-Beetroot.jpg','Fresh-Beetroot-1.jpg','Fresh-Beetroot-2.jpg','Fresh-Beetroot-3.jpg'] },
  { name: 'Brussels Sprouts', price: 120, description: 'Tender Brussels sprouts with a slightly nutty flavor. Perfect for roasting, sautéing, or steaming. Rich in vitamins C and K, adding nutritious variety to your meals.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Brussels Sprouts','Green','Nutritious','Healthy'], images: ['Brussels-Sprouts.jpg'] },
  { name: 'Fresh Cabbage', price: 25, description: 'Crisp green cabbage heads with tightly packed leaves. Versatile for salads, stir-fries, or traditional sabzi. Low in calories and high in vitamin C for everyday cooking.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Cabbage','Green','Fresh','Crunchy'], images: ['Fresh-Cabbage.jpg','Fresh-Cabbage-2.png'] },
  { name: 'Fresh Cauliflower', price: 30, description: 'White cauliflower with compact florets and mild taste. Perfect for curries, parathas, or rice alternatives. Packed with vitamins and antioxidants for wholesome family meals.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Cauliflower','White','Fresh','Versatile'], images: ['Fresh-Cauliflower.png'] },
  { name: 'Fresh Cherries', price: 450, description: 'Juicy red cherries with sweet-tart flavor and firm texture. Great for snacking, baking, or making preserves. Rich in antioxidants and vitamins for a healthy treat.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Cherry','Red','Sweet','Antioxidants'], images: ['Fresh-Cherries.jpg','Fresh-Cherries-2.jpg','Fresh-Cherries-3.jpg','Fresh-Cherries-4.jpg'] },
  { name: 'Fresh Corn', price: 20, description: 'Sweet corn cobs with tender golden kernels. Perfect for grilling, boiling, or adding to salads and curries. High in fiber and natural sugars for satisfying meals.', category: 'Vegetables', stockUnit: 'piece', tags: ['Vegetables','Corn','Sweet','Yellow','Fresh'], images: ['Fresh-Corn.jpg','Fresh-Corn-1.jpg','Fresh-Corn-2.png'] },
  { name: 'Fresh Cucumber', price: 30, description: 'Cool and crisp cucumbers with refreshing taste. Perfect for salads, raita, or fresh juices. Low in calories and high in water content, ideal for hydration.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Cucumber','Green','Fresh','Hydrating'], images: ['Fresh-Cucumber.jpg','Fresh-Cucumber-1.jpg','Fresh-Cucumber-2.png'] },
  { name: 'Fresh Eggplant', price: 35, description: 'Purple eggplants with glossy skin and creamy flesh. Excellent for bharta, curries, and grilling. Rich in fiber and antioxidants, bringing versatility to your kitchen.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Eggplant','Brinjal','Purple','Fresh'], images: ['Fresh-Eggplant.jpg','Fresh-Eggplant-1.jpg','Fresh-Eggplant-2.png'] },
  { name: 'Farm Fresh Eggs', price: 60, description: 'Free-range eggs with rich golden yolks and superior taste. High-quality protein source for breakfast and baking. Fresh from local farms for nutritious, delicious meals.', category: 'Dairy & Eggs', stockUnit: 'dozen', tags: ['Dairy','Eggs','Protein','Fresh','Farm'], images: ['Farm-Fresh-Eggs.jpg'] },
  { name: 'Fresh Garlic', price: 80, description: 'Aromatic garlic bulbs with pungent flavor and firm cloves. Essential for Indian cooking, tadka, and marinades. Known for health benefits and adding depth to every dish.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Garlic','Aromatic','Spice','Fresh'], images: ['Fresh-Garlic.jpg','Fresh-Garlic-1.jpg'] },
  { name: 'Green Apple', price: 120, description: 'Crisp green apples with tangy-sweet flavor. Perfect for snacking, salads, or baking. High in fiber and vitamin C for healthy eating habits.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Apple','Green','Tangy','Crisp'], images: ['Green-Apple.png'] },
  { name: 'Green Chilli', price: 25, description: 'Fresh green chilies adding spice and flavor to dishes. Essential for Indian curries, chutneys, and tempering. Rich in vitamins while boosting metabolism naturally.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Chilli','Green','Spicy','Hot'], images: ['Green-Chilli.jpg','Green-Chilli-2.png'] },
  { name: 'Green Lettuce', price: 50, description: 'Fresh crisp lettuce with tender green leaves. Perfect for salads, wraps, and sandwiches. Low in calories and packed with vitamins for light, healthy meals.', category: 'Vegetables', stockUnit: 'piece', tags: ['Vegetables','Lettuce','Green','Salad','Fresh'], images: ['Green-Lettuce.png'] },
  { name: 'Green Capsicum', price: 60, description: 'Fresh green bell peppers with crisp texture and mild taste. Great for stir-fries, stuffing, and salads. Loaded with vitamin C and antioxidants for nutritious cooking.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Capsicum','Bell Pepper','Green','Fresh'], images: ['Green-Capsicum.jpg','Green-Capsicum-2.png'] },
  { name: 'Premium Cashews', price: 650, description: 'Whole cashew nuts with creamy texture and buttery flavor. Perfect for snacking, sweets, and garnishing. Rich in healthy fats, protein, and minerals for balanced nutrition.', category: 'Dry Fruits', stockUnit: 'kg', tags: ['Dry Fruits','Cashew','Kaju','Nuts','Premium'], images: ['Premium-Cashews.jpg'] },
  { name: 'Fresh Kale', price: 80, description: 'Nutrient-dense kale with dark green curly leaves. Excellent for salads, smoothies, and sautéing. Packed with vitamins, minerals, and antioxidants for superfood nutrition.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Kale','Superfood','Green','Healthy'], images: ['Fresh-Kale.jpg','Fresh-Kale-1.jpg','Fresh-Kale-2.jpg','Fresh-Kale-3.jpg'] },
  { name: 'Fresh Okra', price: 40, description: 'Tender okra pods perfect for traditional Indian bhindi. Ideal for stir-fries and curries. Rich in fiber, vitamins, and minerals supporting digestive health.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Okra','Ladyfinger','Bhindi','Fresh'], images: ['Fresh-Okra.png'] },
  { name: 'Fresh Lemon', price: 60, description: 'Juicy lemons with tangy flavor and bright yellow color. Essential for cooking, drinks, and garnishing. High in vitamin C, boosting immunity and adding zest to meals.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Lemon','Citrus','Tangy','Vitamin C'], images: ['Fresh-Lemon.jpg','Fresh-Lemon-2.jpg'] },
  { name: 'Fresh Mango', price: 100, description: 'Sweet mangoes with juicy golden flesh and tropical aroma. Perfect for eating fresh, smoothies, or desserts. The king of fruits, rich in vitamins A and C.', category: 'Fresh Fruit', stockUnit: 'dozen', tags: ['Fresh Fruit','Mango','Tropical','Sweet','Seasonal'], images: ['Fresh-Mango.png'] },
  { name: 'Fresh Onion', price: 35, description: 'Fresh onions with layers of flavor essential for Indian cooking. Perfect for curries, salads, and tempering. Adds depth and taste to every savory dish.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Onion','Fresh','Essential','Cooking'], images: ['Fresh-Onion.jpg','Fresh-Onion-1.jpg','Fresh-Onion-2.jpg'] },
  { name: 'Fresh Orange', price: 80, description: 'Juicy oranges bursting with sweet citrus flavor. Perfect for fresh juice or snacking. Loaded with vitamin C and natural sugars for refreshing nutrition.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Orange','Citrus','Juicy','Vitamin C'], images: ['Fresh-Orange.jpg','Fresh-Orange-2.jpg','Fresh-Orange-3.jpg','Fresh-Orange-4.jpg'] },
  { name: 'Raw Peanuts', price: 90, description: 'Fresh raw peanuts perfect for roasting and cooking. Great for making chutney, snacks, or oil. High in protein and healthy fats for nutritious eating.', category: 'Dry Fruits', stockUnit: 'kg', tags: ['Dry Fruits','Peanut','Protein','Groundnut','Healthy'], images: ['Raw-Peanuts.jpg'] },
  { name: 'Fresh Pear', price: 150, description: 'Sweet juicy pears with soft texture and delicate flavor. Perfect for snacking, salads, or desserts. Rich in fiber and antioxidants for healthy indulgence.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Pear','Sweet','Juicy','Premium'], images: ['Fresh-Pear.jpg'] },
  { name: 'Fresh Green Peas', price: 50, description: 'Tender green peas with natural sweetness. Perfect for pulao, curries, and mixed vegetables. High in protein and fiber for wholesome vegetarian meals.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Peas','Green','Fresh','Protein'], images: ['Fresh-Green-Peas.jpg','Fresh-Green-Peas-1.jpg','Fresh-Green-Peas-2.jpg'] },
  { name: 'Fresh Pomegranate', price: 120, description: 'Ruby-red pomegranate with juicy sweet-tart arils. Perfect for snacking, juices, or garnishing. Rich in antioxidants and vitamins for healthy living.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Pomegranate','Red','Antioxidants','Healthy'], images: ['Fresh-Pomegranate.jpg','Fresh-Pomegranate-2.jpg'] },
  { name: 'Fresh Potatoes', price: 25, description: 'Versatile potatoes perfect for any dish. Great for frying, mashing, curries, or roasting. A staple vegetable rich in carbohydrates and essential nutrients.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Potato','Fresh','Staple','Versatile'], images: ['Fresh-Potatoes.png'] },
  { name: 'Fresh Pumpkin', price: 30, description: 'Orange pumpkin with sweet flesh and smooth texture. Perfect for curries, soups, and traditional dishes. Rich in beta-carotene and fiber for healthy cooking.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Pumpkin','Orange','Sweet','Nutritious'], images: ['Fresh-Pumpkin.jpg','Fresh-Pumpkin-2.jpg'] },
  { name: 'Fresh Raspberries', price: 400, description: 'Delicate raspberries with sweet-tart flavor and vibrant color. Perfect for desserts, smoothies, or fresh eating. Packed with antioxidants and vitamins for premium nutrition.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Raspberry','Berries','Premium','Antioxidants'], images: ['Fresh-Raspberries.jpg','Fresh-Raspberries-2.jpg'] },
  { name: 'Red Chilli', price: 150, description: 'Fiery red chilies adding intense heat and color. Essential for Indian masalas, curries, and tempering. Dried or fresh, they bring authentic spice to cooking.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Chilli','Red','Spicy','Hot'], images: ['Red-Chilli.jpg','Red-Chilli-2.png'] },
  { name: 'Red Capsicum', price: 100, description: 'Sweet red bell peppers with vibrant color and crunchy texture. Perfect for salads, grilling, and stir-fries. Exceptionally high in vitamin C and antioxidants.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Capsicum','Bell Pepper','Red','Sweet'], images: ['Red-Capsicum.png'] },
  { name: 'Fresh Strawberries', price: 250, description: 'Sweet red strawberries with juicy flesh and aromatic flavor. Perfect for desserts, smoothies, or eating fresh. Rich in vitamin C and antioxidants for delicious nutrition.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Strawberry','Berries','Sweet','Red'], images: ['Fresh-Strawberries.jpg','Fresh-Strawberries-2.jpg','Fresh-Strawberries-3.jpg'] },
  { name: 'Fresh Tangerine', price: 70, description: 'Easy-to-peel tangerines with sweet citrus flavor. Perfect for snacking and fresh juice. Loaded with vitamin C and natural sweetness for refreshing taste.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Tangerine','Citrus','Sweet','Easy Peel'], images: ['Fresh-Tangerine.jpg'] },
  { name: 'Fresh Tomatoes', price: 30, description: 'Juicy red tomatoes perfect for Indian cooking. Essential for curries, salads, and sauces. Rich in lycopene and vitamins for everyday nutritious meals.', category: 'Vegetables', stockUnit: 'kg', tags: ['Vegetables','Tomato','Red','Fresh','Essential'], images: ['Fresh-Tomatoes.jpg','Fresh-Tomatoes-1.jpg','Fresh-Tomatoes-2.png'] },
  { name: 'Premium Walnuts', price: 800, description: 'Whole walnuts with rich flavor and crunchy texture. Perfect for snacking, desserts, and garnishing. Loaded with omega-3 fatty acids and antioxidants for brain health.', category: 'Dry Fruits', stockUnit: 'kg', tags: ['Dry Fruits','Walnut','Nuts','Omega-3','Premium'], images: ['Premium-Walnuts.jpg'] },
  { name: 'Fresh Watermelon', price: 40, description: 'Sweet red watermelon with juicy, refreshing flesh. Perfect summer fruit for hydration and cooling. Low in calories and high in vitamins for healthy snacking.', category: 'Fresh Fruit', stockUnit: 'kg', tags: ['Fresh Fruit','Watermelon','Red','Hydrating','Summer'], images: ['Fresh-Watermelon.jpg'] },
  { name: 'Milk', price: 60, description: 'Fresh and creamy milk, perfect for drinking or cooking. Rich in calcium and essential nutrients for a healthy diet.', category: 'Dairy', stockUnit: 'litre', tags: ['Dairy','Milk','Fresh','Creamy','Calcium'], images: ['Milk.jpg','Milk-1.jpg'] },
  { name: 'Cheese', price: 200, description: 'Rich and creamy cheese, perfect for snacking or cooking. Loaded with calcium and protein for a healthy diet.', category: 'Dairy', stockUnit: 'kg', tags: ['Dairy','Cheese','Creamy','Protein','Calcium'], images: ['Cheese.jpg','Cheese-2.png'] },
  { name: 'Paneer', price: 250, description: 'Fresh and soft paneer, perfect for Indian dishes. High in protein and calcium for a nutritious diet.', category: 'Dairy', stockUnit: 'kg', tags: ['Dairy','Paneer','Fresh','Soft','Protein'], images: ['Paneer.png'] },
];
